### PR TITLE
Allow User To Click On 3 Endpoints To View Sample Data

### PR DESCRIPTION
**Pull request by jxb345**

### CODE REVIEW

**Comment by MuhammadJamaluddin** [comment]
Here's some quick issues I've noticed:
1- I see a lot of stylistic issues (some missing semi-colons, no newline at end file & others).
2- should stick to using `const` (that should do it for most cases unless you wanna reassign) & `let`.
3- I would install the airbnb eslint config to make these stylistic issues fast to discover while developing.

**Comment by jxb345** [comment]
As per your suggestion, I've installed airbnb eslint config and fixed the highlighted errors. Also, I took the opportunity add and complete a section of the ReadME titled, "API Endpoints." Finally, there is a known issue in my code when trying to run the seed script a second time - this is due to the associations between the two tables: 'authors' and 'books'. I am looking into this now.

**Comment by MuhammadJamaluddin** [comment]
Thanks @jxb345 for the improvements you're made.
Some suggested changes:
1- Update the (API endpoints) section in the README to make the objects appear in code blocks (more readable on Github).
2- Update the usage section to include the instructions needed to get the app up & running (I had a hard time finding my way).
3- A small typo at (line 33) within the express server (index.js).

**Comment by jxb345** [comment]
Thanks, @MuhammadJamaluddin ! I've implemented each of your three suggestions!

**Pull request merged**
